# Generated by Django 3.2.7 on 2021-09-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210919_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturelist',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sectionlist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
